name: Build Docker Image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Building the Docker Image
      run: |
        ./scripts/build.sh
